-- Compact strict-teammate graph for a fresh TeamMateTag Supabase project.
--
-- The former proof tables repeated sport, season, and pair metadata for every
-- edge (2.89M rows).  This stores each exact team-season edge twice, once in
-- each player's bounded adjacency row.  Team metadata remains normalized in
-- compact_team_keys.  Runtime reads start with the player's primary-key row,
-- so this deliberately has no reverse proof index.

DO $$
DECLARE relation_name TEXT;
BEGIN
  FOREACH relation_name IN ARRAY ARRAY[
      'compact_mlb_teammate_game_proofs', 'compact_sport_teammates',
      'mlb_teammate_game_proofs', 'sport_teammates'
  ] LOOP
    IF EXISTS (SELECT 1 FROM pg_class WHERE oid = to_regclass(relation_name)
               AND relkind IN ('r', 'p')) THEN
      EXECUTE format('DROP TABLE %I CASCADE', relation_name);
    ELSIF EXISTS (SELECT 1 FROM pg_class WHERE oid = to_regclass(relation_name)
                  AND relkind = 'v') THEN
      EXECUTE format('DROP VIEW %I CASCADE', relation_name);
    END IF;
  END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS compact_player_keys (
    player_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope TEXT NOT NULL,
    player_id TEXT NOT NULL,
    UNIQUE (scope, player_id)
);

CREATE TABLE IF NOT EXISTS compact_team_keys (
    team_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope TEXT NOT NULL,
    team_id TEXT NOT NULL,
    season SMALLINT NOT NULL,
    UNIQUE (scope, team_id, season)
);

CREATE INDEX IF NOT EXISTS idx_compact_player_scope_id
    ON compact_player_keys(scope, player_id);
CREATE INDEX IF NOT EXISTS idx_compact_team_scope_id_season
    ON compact_team_keys(scope, team_id, season);

CREATE TABLE IF NOT EXISTS compact_teammate_adjacency (
    player_key INTEGER PRIMARY KEY
        REFERENCES compact_player_keys(player_key) ON DELETE CASCADE,
    edge_codes BIGINT[] NOT NULL DEFAULT '{}'::BIGINT[],
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- This table is intentionally limited to the currently-updating season for
-- each sport.  It lets a daily updater replace that season's edges without
-- retaining raw game rows or a second historical proof matrix in Postgres.
CREATE TABLE IF NOT EXISTS compact_live_season_proofs (
    scope TEXT NOT NULL,
    season SMALLINT NOT NULL,
    player_a_key INTEGER NOT NULL REFERENCES compact_player_keys(player_key),
    player_b_key INTEGER NOT NULL REFERENCES compact_player_keys(player_key),
    team_key INTEGER NOT NULL REFERENCES compact_team_keys(team_key),
    PRIMARY KEY (scope, season, player_a_key, player_b_key, team_key),
    CHECK (player_a_key <> player_b_key)
);
CREATE INDEX IF NOT EXISTS idx_compact_live_proofs_scope_season
    ON compact_live_season_proofs(scope, season);

-- Directed compatibility views. Existing compact query paths always begin by
-- filtering player_a_key, which resolves a single adjacency row before
-- unnesting its small payload. They keep the rest of the game functional while
-- the graph no longer needs a giant reverse-direction index.
CREATE VIEW compact_mlb_teammate_game_proofs AS
SELECT adjacency.player_key AS player_a_key,
       (edge.edge_code >> 32)::INTEGER AS player_b_key,
       (edge.edge_code & 4294967295)::INTEGER AS team_key,
       team.season,
       1::SMALLINT AS shared_games,
       0::INTEGER AS first_game_pk,
       make_date(team.season, 1, 1) AS first_game_date
  FROM compact_teammate_adjacency adjacency
 CROSS JOIN LATERAL unnest(adjacency.edge_codes) AS edge(edge_code)
  JOIN compact_team_keys team
    ON team.team_key = (edge.edge_code & 4294967295)::INTEGER
 WHERE team.scope = 'baseball';

CREATE VIEW compact_sport_teammates AS
SELECT team.scope AS sport_id,
       adjacency.player_key AS player_a_key,
       (edge.edge_code >> 32)::INTEGER AS player_b_key,
       team.team_key,
       team.season
  FROM compact_teammate_adjacency adjacency
 CROSS JOIN LATERAL unnest(adjacency.edge_codes) AS edge(edge_code)
  JOIN compact_team_keys team
    ON team.team_key = (edge.edge_code & 4294967295)::INTEGER
 WHERE team.scope <> 'baseball';

-- Canonical compatibility views are for legacy validation paths. Gameplay
-- uses the directed compact views above and starts at the current player.
CREATE VIEW mlb_teammate_game_proofs AS
SELECT a.player_id AS player_a_id,
       b.player_id AS player_b_id,
       team.team_id,
       team.season,
       1::INTEGER AS shared_games,
       0::INTEGER AS first_game_pk,
       make_date(team.season, 1, 1) AS first_game_date,
       'compact_adjacency'::TEXT AS source
  FROM compact_mlb_teammate_game_proofs proof
  JOIN compact_player_keys a ON a.player_key = proof.player_a_key
  JOIN compact_player_keys b ON b.player_key = proof.player_b_key
  JOIN compact_team_keys team ON team.team_key = proof.team_key
 WHERE proof.player_a_key < proof.player_b_key;

CREATE VIEW sport_teammates AS
SELECT team.scope AS sport_id,
       a.player_id AS player_a_id,
       b.player_id AS player_b_id,
       team.team_id,
       team.season
  FROM compact_sport_teammates proof
  JOIN compact_player_keys a ON a.player_key = proof.player_a_key
  JOIN compact_player_keys b ON b.player_key = proof.player_b_key
  JOIN compact_team_keys team ON team.team_key = proof.team_key
 WHERE proof.player_a_key < proof.player_b_key;
